# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

def available_pods
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
end

target 'MovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB
  available_pods

  target 'MovieDBTests' do
    # Pods for testing
    inherit! :search_paths
    available_pods
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'MovieDBUITests' do
    # Pods for testing
    inherit! :search_paths
    available_pods
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "5.0"
        end
    end
end
